### PR TITLE
Add support for mvnpm sources classifier

### PR DESCRIPTION
**Pull request by ia3andy**
@phillip-kruger I am not sure about supporting sources for grouped package because I don't have access to the groupid

Fixes https://github.com/mvnpm/esbuild-java/issues/68

### CODE REVIEW

**Comment by phillip-kruger** [comment]
How do you mean ?

**Comment by ia3andy** [comment]
> How do you mean ?

There is no pom.xml in the jar

**Comment by phillip-kruger** [comment]
Mmm, that is a problem. There should be one. Are you looking at the source or normal jar?

**Comment by ia3andy** [comment]
> Mmm, that is a problem. There should be one. Are you looking at the source or normal jar?

This PR allows support for the `sources` classifier, so `sources`

**Pull request merged**
