### PR TITLE
added esbuild version to the config

### PR DESCRIPTION
**Pull request by edewit**
fixes: #88

### CODE REVIEW

**Review by ia3andy — CHANGES_REQUESTED** [review]
You also need a setter in the EsBuildCOnfigBuilder

**Comment by ia3andy** [comment]
I am wondering if we should:
- have the default version embedded when null (like we currently do)
- Allow to pick the source of the build with an enum (ORIGINAL_ESBUILD, MVNPM_ESBUILD) and have url constant for both 
- Allow to pick a specific version

**Comment by edewit** [comment]
Why have an enum with ORIGINAL_ESBUILD and MVNPM_ESBUILD the only difference is the added plugin, when you don't have any scss or sass there is no difference

**Review by ia3andy — APPROVED** [review]

**Comment by ia3andy** [comment]
@edewit you need to format the code

**Pull request merged**
